version: '3'

services:
  frontend:
    image: nginx:1.13
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      # Mapeamento da configuração do proxy reverso
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
  app:
    image: node:8
    volumes:
      # Mapeamento do aplcativo
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    command: bash app.sh
    
